// datasm.js — Data statis Sekolah Model 2026 (diperbarui: 30 Mei 2026)
// Menggantikan fetch ke Google Apps Script untuk data dashboard.

const BERANDA_SCHOOLS = [
  {
    "no": 1,
    "npsn": "10107097",
    "nama": "SMA NEGERI 2 BIREUEN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Aceh",
    "kabkota": "Kab. Bireuen",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1k0orsTfRxVVfnyGoprNi4uHdtRxAc-O3&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Uobvfl7URSuyedEkS-K1qBUcPtKR-k6-&usp=drive_copy"
  },
  {
    "no": 2,
    "npsn": "10105399",
    "nama": "SMA NEGERI 2 BANDA ACEH",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Aceh",
    "kabkota": "Kota Banda Aceh",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1k0orsTfRxVVfnyGoprNi4uHdtRxAc-O3&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Tvg-pMP7-gbcbo3JBCiOwZifFLD6su0T&usp=drive_copy"
  },
  {
    "no": 3,
    "npsn": "10105388",
    "nama": "SMA NEGERI 3 BANDA ACEH",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Aceh",
    "kabkota": "Kota Banda Aceh",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1k0orsTfRxVVfnyGoprNi4uHdtRxAc-O3&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1tk7psCqK4YZCzBCuencw9n2nC0CPWkVB&usp=drive_copy"
  },
  {
    "no": 4,
    "npsn": "50103126",
    "nama": "SMA Negeri 2 Denpasar",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Bali",
    "kabkota": "Kota Denpasar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1vCtEPTUhks6uv1HrEA3q1dx0aYNPzwjq&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1TPRL-n9k0aK_wM5lC4_4eLtnWjsdptBV/view?usp=sharing"
  },
  {
    "no": 5,
    "npsn": "50103124",
    "nama": "SMA Negeri 4 Denpasar",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Bali",
    "kabkota": "Kota Denpasar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1vCtEPTUhks6uv1HrEA3q1dx0aYNPzwjq&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=15gZQf4haBORvm4Z8CzCkmL9s7lx1fr0I&usp=drive_copy"
  },
  {
    "no": 6,
    "npsn": "50103181",
    "nama": "SMAS K SANTO YOSEPH DENPASAR",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Bali",
    "kabkota": "Kota Denpasar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 7,
    "npsn": "20600451",
    "nama": "SMAN 1 PANDEGLANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kab. Pandeglang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1_-tzVwTq7YiY17DlRiZSU-rdFuZN9mrT/view?usp=drive_link"
  },
  {
    "no": 8,
    "npsn": "20605105",
    "nama": "SMAN 1 JAWILAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kab. Serang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1_-tzVwTq7YiY17DlRiZSU-rdFuZN9mrT/view?usp=drive_link"
  },
  {
    "no": 9,
    "npsn": "20605108",
    "nama": "SMAN 1 Kramatwatu",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kab. Serang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1n-Cf7RooQgJetIsnbtNuVPf3TlrORApK&usp=drive_copy"
  },
  {
    "no": 10,
    "npsn": "20606289",
    "nama": "SMAN 1 CILEGON",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kota Cilegon",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=170dPGpSWBoqz7H5kpCD_zaY2pHIO8Z0U&usp=drive_copy"
  },
  {
    "no": 11,
    "npsn": "20613477",
    "nama": "SMAN 2 KOTA TANGERANG SELATAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kota Tangerang Selatan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1nmz0G0TXbufLfP8i6iHzTjqaXzJsZ3bC&usp=drive_copy"
  },
  {
    "no": 12,
    "npsn": "69973317",
    "nama": "SMAS HELLOMOTION",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Banten",
    "kabkota": "Kota Tangerang Selatan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=15F9niqGVMRQmslaTY_zUi2Z97T2KP9Iz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1hKKjaj5Tu-l6PnGDg8sZTowEpTukM2Yy&usp=drive_copy"
  },
  {
    "no": 13,
    "npsn": "10700887",
    "nama": "SMA NEGERI 9 BENGKULU SELATAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Bengkulu",
    "kabkota": "Kab. Bengkulu Selatan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1qFLqLELqfVZFrpA6v_rMVja7HMNgajGM&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1-pzh-WpQeVIAcO5phMvQivpd74k9BNL4/view?usp=drive_link"
  },
  {
    "no": 14,
    "npsn": "10701981",
    "nama": "SMA NEGERI 3 LEBONG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Bengkulu",
    "kabkota": "Kab. Lebong",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1qFLqLELqfVZFrpA6v_rMVja7HMNgajGM&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1HrhB-uxxijmKOi5Hnp4mXxe5SXP6-OA6/view?usp=drive_link"
  },
  {
    "no": 15,
    "npsn": "70042675",
    "nama": "SMAIT KHOIRU UMMAH",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Bengkulu",
    "kabkota": "Kab. Rejang Lebong",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/17vU5BNKRhjFYWM_74XLBheB7PGi7zybj/view?usp=sharing"
  },
  {
    "no": 16,
    "npsn": "69879000",
    "nama": "SMA IT IQRA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Bengkulu",
    "kabkota": "Kota Bengkulu",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1Hbyw6u4GIrt06pjlpy2eiD7-WljUxQIh/view?usp=sharing"
  },
  {
    "no": 17,
    "npsn": "10702460",
    "nama": "SMAS MUHAMMADIYAH 4 Bengkulu",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Bengkulu",
    "kabkota": "Kota Bengkulu",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1g0tpeq3QX-xGChu9Dh2lK5gvxQR4jb_3"
  },
  {
    "no": 18,
    "npsn": "20402055",
    "nama": "SMA MUHAMMADIYAH Al MUJAHIDIN WONOSARI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kab. Gunungkidul",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=12vYfJtyjip35jjX9gS3AOc_zbCEoiPF7"
  },
  {
    "no": 19,
    "npsn": "20402054",
    "nama": "SMA PEMBANGUNAN 3 PONJONG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kab. Gunungkidul",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1vQoDaeDtPUA8qmDaokKLpF-lYwLUBmYz/view?usp=drive_link"
  },
  {
    "no": 20,
    "npsn": "70032208",
    "nama": "SMA BUMI CENDEKIA",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kab. Sleman",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1-QbjB6lRPGAbB862YG3ZFt0W53o-fX9E&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1oNPa2Ut6K7PjfLgxgpgYKZMUguHTQM-w&usp=drive_copy"
  },
  {
    "no": 21,
    "npsn": "60724851",
    "nama": "SMA MUHAMMADIYAH BOARDING SCHOOL SLEMAN YOGYAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kab. Sleman",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1I4FRUSsbk1NedpaqGVCXqW5A49maizAp"
  },
  {
    "no": 22,
    "npsn": "20403180",
    "nama": "SMAN 5 YOGYAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kota Yogyakarta",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1-QbjB6lRPGAbB862YG3ZFt0W53o-fX9E&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1una2vMZdgHsFXaWYcJA4qHq-op4IIF9G&usp=drive_copy"
  },
  {
    "no": 23,
    "npsn": "20403157",
    "nama": "SMAS MUHAMMADIYAH 1 YOGYAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kota Yogyakarta",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1W8Ub7krCJm6rOhvNdwf0FlRsH6f_EsM_"
  },
  {
    "no": 24,
    "npsn": "20403158",
    "nama": "SMAS MUHAMMADIYAH 2 YOGYAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kota Yogyakarta",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1RKZHexMhQdzA07UdJDcAl3TTxqj4rP-E/view"
  },
  {
    "no": 25,
    "npsn": "20403149",
    "nama": "SMAS MUHAMMADIYAH 3 YOGYAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.I. Yogyakarta",
    "kabkota": "Kota Yogyakarta",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1SKbHCcXQGFHzWtXT5QLdhziKoi51nUqq"
  },
  {
    "no": 26,
    "npsn": "20107314",
    "nama": "SMA MUHAMMADIYAH 3 JAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Selatan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1R6kleCndiRC9BXvrbn0pI3ZaZVUAwFDb"
  },
  {
    "no": 27,
    "npsn": "20107319",
    "nama": "SMAN 28 JAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Selatan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1l_weWEtjyk_wfOUFhZzUTLAlekmbI8Ai/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/19Y_xSOOaVzZMXTCFGJAB5xKVCyZ0dRls/view?usp=sharing"
  },
  {
    "no": 28,
    "npsn": "20102573",
    "nama": "SMAN 60 JAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Selatan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1l_weWEtjyk_wfOUFhZzUTLAlekmbI8Ai/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/19Y_xSOOaVzZMXTCFGJAB5xKVCyZ0dRls/view?usp=sharing"
  },
  {
    "no": 29,
    "npsn": "20107315",
    "nama": "SMAS MUHAMMADIYAH 18 JAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Selatan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1wI4XIWQePrr3DZkhySuiLf5DfiFdTtaT"
  },
  {
    "no": 30,
    "npsn": "20103293",
    "nama": "SMAN 102 JAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Timur",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1l_weWEtjyk_wfOUFhZzUTLAlekmbI8Ai/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/19Y_xSOOaVzZMXTCFGJAB5xKVCyZ0dRls/view?usp=sharing"
  },
  {
    "no": 31,
    "npsn": "20103283",
    "nama": "SMAN 21 JAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1l_weWEtjyk_wfOUFhZzUTLAlekmbI8Ai/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/19Y_xSOOaVzZMXTCFGJAB5xKVCyZ0dRls/view?usp=sharing"
  },
  {
    "no": 32,
    "npsn": "20103220",
    "nama": "SMAS FRANSISKUS 2 JAKARTA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. D.K.I. Jakarta",
    "kabkota": "Kota Adm. Jakarta Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 33,
    "npsn": "70015681",
    "nama": "SMA ISLAM TERPADU AL ISHLAH",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Gorontalo",
    "kabkota": "Kota Gorontalo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1uplEeplf1iEEgoV_--iRM0MlDv-Sqp8R/view?usp=sharing"
  },
  {
    "no": 34,
    "npsn": "40501083",
    "nama": "SMAN 3 GORONTALO",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Gorontalo",
    "kabkota": "Kota Gorontalo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1X7VYNpLvtqvcqoqh8GkBi-kSR0R3ogfW/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1b1yUWSjQJGrtpICFk-qrYk81nPOaU5dF&usp=drive_copy"
  },
  {
    "no": 35,
    "npsn": "10502401",
    "nama": "SMAN 2 KERINCI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jambi",
    "kabkota": "Kab. Kerinci",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1CXXcPQEbdSTGbvU5bI8S9G1kt1hBH3ij/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Hcj5QGj0hGVmsKyp8_jdWKUV5SG_po8v/view?usp=sharing"
  },
  {
    "no": 36,
    "npsn": "10504581",
    "nama": "SMAN 5 KOTA JAMBI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jambi",
    "kabkota": "Kota Jambi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1CXXcPQEbdSTGbvU5bI8S9G1kt1hBH3ij/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1mNhE9QOx9Pjqzheh32Tczp1aDxCc0kt9/view?usp=drive_link"
  },
  {
    "no": 37,
    "npsn": "20227871",
    "nama": "SMA PGRI 31 PANGALENGAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bandung",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1IQV47JQkki084vg2P9DyqesI5Sxmiej3/view"
  },
  {
    "no": 38,
    "npsn": "20251784",
    "nama": "SMA PGRI CICALENGKA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bandung",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Tjj3cVXY6zcWcprRa6zJrRJJnEmmgr3y&usp=drive_copy"
  },
  {
    "no": 39,
    "npsn": "20206211",
    "nama": "SMA NEGERI 1 LEMBANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bandung Barat",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1k-VlQSFeVLtxeWKjhIJ6PSW5QZ8lDmjy&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1UejV1oc1f3M8Pl0fNE3Qebal5oCYg5nG/view?usp=drive_link"
  },
  {
    "no": 40,
    "npsn": "20200691",
    "nama": "SMAN 2 CIBINONG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bogor",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1J-TiFaoZJFCqr6Cul_7LS2iIk3XaZff1&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1k5semsxUOOZZArhKT9_kzF7J5iBfQUJn&usp=drive_copy"
  },
  {
    "no": 41,
    "npsn": "69918146",
    "nama": "SMAN 4 CIBINONG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bogor",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1J-TiFaoZJFCqr6Cul_7LS2iIk3XaZff1&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1J-TiFaoZJFCqr6Cul_7LS2iIk3XaZff1&usp=drive_copy"
  },
  {
    "no": 42,
    "npsn": "20232396",
    "nama": "SMAS PGRI CIBINONG",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Bogor",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1J-TiFaoZJFCqr6Cul_7LS2iIk3XaZff1&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1EXf2EuDQip0mCIB1dSKcNVA8DbeOY9OV&usp=drive_copy"
  },
  {
    "no": 43,
    "npsn": "20211500",
    "nama": "SMAN 2 CIAMIS",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Ciamis",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1rwini50Qa4bWVS2L3osU_zt0--qpn8qv&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1kV2YtpK-JcKzCLPAugNQyLMPrWFRj0ZP&usp=drive_copy"
  },
  {
    "no": 44,
    "npsn": "20203723",
    "nama": "SMAN 2 CIANJUR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Cianjur",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1k-VlQSFeVLtxeWKjhIJ6PSW5QZ8lDmjy&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1sm_kBXF2LqVdTdZcis4ig8MyNa1LeImo/view?usp=sharing"
  },
  {
    "no": 45,
    "npsn": "20214995",
    "nama": "SMAN 1 LEMAHABANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Cirebon",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1_HmS57Qtwgy4mCSv_kOKMCO2WuPR5Tvy&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1wIqBlinxObS7IM85r7wyP-e8UMmWLxCE&usp=drive_copy"
  },
  {
    "no": 46,
    "npsn": "20253399",
    "nama": "SMAS MAARIF BANYURESMI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Garut",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1KqOo8ilm_L-s0XEaMM1y9XgyV1oEx40p/view?usp=drive_link"
  },
  {
    "no": 47,
    "npsn": "20227449",
    "nama": "SMAS PGRI KURNIA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Garut",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1qbxR2EoaP55sp6P4lDNxT3to913GTQ7l&usp=drive_copy"
  },
  {
    "no": 48,
    "npsn": "20216200",
    "nama": "SMAS NU KAPLONGAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Indramayu",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1shiAEQdi28Y2EDCSX-QJVVsRV0QdYQAj/view?usp=drive_link"
  },
  {
    "no": 49,
    "npsn": "69892332",
    "nama": "SMA IT NURUL BAROKAH",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Majalengka",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1dxVpe6RXoFcfileY08aU-Ycb9k77bgLS/view?usp=drive_link"
  },
  {
    "no": 50,
    "npsn": "69900793",
    "nama": "SMA NURUL FAJRI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Majalengka",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": null
  },
  {
    "no": 51,
    "npsn": "70010870",
    "nama": "SMA Fullday Al-Muhajirin",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Purwakarta",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/19AeC4Y7gi9_K8uFzRLLIPvSSYYGF4GL9/view?usp=drive_link"
  },
  {
    "no": 52,
    "npsn": "20216937",
    "nama": "SMAN 2 SUBANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Subang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1ocwmP6Yt0EjTNcGeVxJN3p0-FhNB1HC0&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1xup6ZmFFGB1MCi_Vb2QGrvsULaoY6vxL&usp=drive_copy"
  },
  {
    "no": 53,
    "npsn": "20202317",
    "nama": "SMAN 1 CIBADAK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Sukabumi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1gnk7StnPnjfSsvpt0lEVlwvnI0jjSDvu&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Q38S-SROyCSZQ3J0CRZw8XU8EDlct2tM&usp=drive_copy"
  },
  {
    "no": 54,
    "npsn": "20210718",
    "nama": "SMAN 1 TARAJU",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kab. Tasikmalaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=10GbuyyJgeSJYDyXuuwgp43-ZgFL_ffWX&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=11A49JhEqdhvldOwnIqqVcGeUJN03r6cn&usp=drive_copy"
  },
  {
    "no": 55,
    "npsn": "20219326",
    "nama": "SMAN 8 BANDUNG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bandung",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1_HhIaVwLFSsXij_rTACkOFbuHEQYuRGP&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1dKSpBYKHa3lVy3qFYtwa_lQiE_uHamqU/view?usp=sharing"
  },
  {
    "no": 56,
    "npsn": "20219800",
    "nama": "SMAS MAARIF BANDUNG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bandung",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1rPFFlp8yKXYjs2pH5EbBGwzUztwV7fRX/view?usp=drive_link"
  },
  {
    "no": 57,
    "npsn": "20219806",
    "nama": "SMAS MUHAMMADIYAH 2",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bandung",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1BYL6qwrDzRtAoFFmeEQjeqz5o-JQmJmh"
  },
  {
    "no": 58,
    "npsn": "69864697",
    "nama": "SMA KRISTEN SAINT JOHN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bekasi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 59,
    "npsn": "20223045",
    "nama": "SMAN 4 BEKASI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bekasi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11Zx52qzHzdTCRWMddkVE2Ss1ReIzQoI8&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1NSDvUWTWwfJQT7Z3m1DDj-XX_8qE1Ltn&usp=drive_copy"
  },
  {
    "no": 60,
    "npsn": "20223075",
    "nama": "SMAS MARSUDIRINI",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bekasi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11Zx52qzHzdTCRWMddkVE2Ss1ReIzQoI8&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1oWvaSRzRog9QvargdLUA71ylX8vsIgb5/view?usp=sharing"
  },
  {
    "no": 61,
    "npsn": "20220342",
    "nama": "SMAN 1 BOGOR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bogor",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1KXHA4blati3wMHCuwZeWQLHuvzA4BIah/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1ZvhVVeMQxHo3z2w0WBwqUipgr1qrQ_Ew&usp=drive_copy"
  },
  {
    "no": 62,
    "npsn": "69775444",
    "nama": "SMAS IT UMMUL QURO",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Bogor",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1e5JA5VyCcb2j1qk8Zl4q7Os_APpbkjPx/view?usp=sharing"
  },
  {
    "no": 63,
    "npsn": "69899184",
    "nama": "SMA MUHAMMADIYAH 04 DEPOK",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Depok",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1k-fxpB9ASM0Ovc0vrde875NZXyRXiVk7"
  },
  {
    "no": 64,
    "npsn": "20223819",
    "nama": "SMAN 1 KOTA DEPOK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Depok",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1KXHA4blati3wMHCuwZeWQLHuvzA4BIah/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1R25GX_1ChoIvW8_n9JFSZZOM-KKdBTnk&usp=drive_copy"
  },
  {
    "no": 65,
    "npsn": "20221559",
    "nama": "SMAN 1 SUKABUMI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Sukabumi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1gnk7StnPnjfSsvpt0lEVlwvnI0jjSDvu&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1174hVoJ6Z1e3IFE4IQE_7K5VRMyxMfGO&usp=drive_copy"
  },
  {
    "no": 66,
    "npsn": "20221587",
    "nama": "SMAS PESANTREN TERPADU HAYATAN THAYYIBAH",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Barat",
    "kabkota": "Kota Sukabumi",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1gnk7StnPnjfSsvpt0lEVlwvnI0jjSDvu&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1r6C0H77j2QC1RnfAQyd9j18p8O5JWNrV&usp=drive_copy"
  },
  {
    "no": 67,
    "npsn": "20302165",
    "nama": "SMA NEGERI 2 PURWOKERTO",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Banyumas",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/17Gm30SH_Fc7bin1pExRlB8WcIbCtr5_d/view?usp=sharing"
  },
  {
    "no": 68,
    "npsn": "20337795",
    "nama": "SMA ISLAM TERPADU AL HIKMAH KARANGGEDE",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Boyolali",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1cj7R0Tg3ndXUaXVexuNcfARNp2bWP_nk/view?usp=sharing"
  },
  {
    "no": 69,
    "npsn": "20319280",
    "nama": "SMA NEGERI 1 DEMAK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Demak",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Eigr7g27Hm8y_ncrIfDwvoN1CoDoipVX/view?usp=sharing"
  },
  {
    "no": 70,
    "npsn": "20318343",
    "nama": "SMA NEGERI 1 JEPARA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Jepara",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1_dlObrXGHpDQkMjiMfSj2i0BtX_6_EK3/view?usp=sharing"
  },
  {
    "no": 71,
    "npsn": "20309676",
    "nama": "SMA NEGERI 1 KLATEN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Klaten",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/18liLCjucDFyYZdLRqa8mgxh-fREEIq0p/view?usp=sharing"
  },
  {
    "no": 72,
    "npsn": "20309729",
    "nama": "SMAS MUHAMMADIYAH 1 KLATEN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Klaten",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1LyCWnlwAHFcVuFl_10Ut85xUJ91b2YJ8"
  },
  {
    "no": 73,
    "npsn": "20350718",
    "nama": "SMA IHSANUL FIKRI MUNGKID",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Magelang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1c2_y_cuEMPcMk3nTo7TbmsgJUBQ-Yb4X/view?usp=sharing"
  },
  {
    "no": 74,
    "npsn": "69980596",
    "nama": "SMA TARUNA MUHAMMADIYAH GUNUNGPRING",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Magelang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=13nz26P8E6QO7bMh9ubi2kY-lHDvU-lnd"
  },
  {
    "no": 75,
    "npsn": "20310425",
    "nama": "SMA NEGERI 1 KARTASURA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Sukoharjo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1aDf-hgQJrJ4a9wY6XhrPN9kas7qseZnI/view?usp=sharing"
  },
  {
    "no": 76,
    "npsn": "20321430",
    "nama": "SMA PGRI TEMANGGUNG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Temanggung",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1e1ZfUYclGIYQxreYQ4EVkkhAmZbXN9YZ/view?usp=drive_link"
  },
  {
    "no": 77,
    "npsn": "20331953",
    "nama": "SMAS MUHAMMADIYAH WONOSOBO",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kab. Wonosobo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1F2jIdqkQwMkO8fjviJhM9fyPXsWT7qtz"
  },
  {
    "no": 78,
    "npsn": "20328920",
    "nama": "SMA ISLAM HIDAYATULLAH",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kota Semarang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/13EYCnOrE6QSyupLpWYgdpjl5X_JlG0K0/view?usp=sharing"
  },
  {
    "no": 79,
    "npsn": "20328895",
    "nama": "SMA NEGERI 3 SEMARANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kota Semarang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1wVI84RmDIISoX0D2UxnwfA3F668aEVME/view?usp=sharing"
  },
  {
    "no": 80,
    "npsn": "20328893",
    "nama": "SMA NEGERI 5 SEMARANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kota Semarang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1esHJFZZfEwB6wonN3BX_KZqp-Tbpqt8T/view?usp=sharing"
  },
  {
    "no": 81,
    "npsn": "69949652",
    "nama": "SMA Muhammadiyah Program Khusus Kottabarat Surakarta",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kota Surakarta",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1HarYdfMB4gXCCYFeW6yjcj5_XiXhv7FX"
  },
  {
    "no": 82,
    "npsn": "20327966",
    "nama": "SMA NEGERI 1 SURAKARTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Tengah",
    "kabkota": "Kota Surakarta",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1aaxPHgZsanZukIh2rZQHw3bppKECjPt6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1sO10VyyiECQtbzG6zVhBNDM4ZJFvT-FV/view?usp=sharing"
  },
  {
    "no": 83,
    "npsn": "20525600",
    "nama": "SMA NEGERI 2 TARUNA BHAYANGKARA JAWA TIMUR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Banyuwangi",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1A_G1ua9TWWa-JR1t-pA5sxb77oyax-A8&usp=drive_copy"
  },
  {
    "no": 84,
    "npsn": "69946189",
    "nama": "SMA MUHAMMADIYAH 10 Gresik",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Gresik",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1fowUM9bcRb_PYnZOq6xPHn4n7wB85m7K"
  },
  {
    "no": 85,
    "npsn": "20500472",
    "nama": "SMA NAHDLATUL ULAMA 1",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Gresik",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1OB5E46TmiWl1RcGVh5fZ2J-ackcDR6JG&usp=drive_copy"
  },
  {
    "no": 86,
    "npsn": "20500474",
    "nama": "SMAN 1 SIDAYU",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Gresik",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1O1Ff_yHZY0z-K4dQA7A7Ox24vMpBzB9S&usp=drive_copy"
  },
  {
    "no": 87,
    "npsn": "20500463",
    "nama": "SMAS MUHAMMADIYAH 1 GRESIK",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Gresik",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1jU8k7FzgF8yNaX2hoGqXvqy4zQdAv9jG"
  },
  {
    "no": 88,
    "npsn": "20520819",
    "nama": "SMAN 3 LUMAJANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Lumajang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1xkyZwd6WmcBGkYKe_gLmNMks-9tzqi-I&usp=drive_copy"
  },
  {
    "no": 89,
    "npsn": "20538324",
    "nama": "SMA NEGERI 1 PATIANROWO NGANJUK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Nganjuk",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1wXKvBFbR7UNg4mG2wxSZaHCez7DMABVn&usp=drive_copy"
  },
  {
    "no": 90,
    "npsn": "20510139",
    "nama": "SMAS MUHAMMADIYAH 1 PONOROGO",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Ponorogo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=12oJxMKXa8CgCZTIIBR1Jtxmf-gdyK9Dk"
  },
  {
    "no": 91,
    "npsn": "20546533",
    "nama": "SMAN 1 GENDING",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Probolinggo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1hRI5qXpa1OCW09ay6TtCPDTdFZYBHryP&usp=drive_copy"
  },
  {
    "no": 92,
    "npsn": "69888642",
    "nama": "SMA PROGRESIF BUMI SHALAWAT",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Sidoarjo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1ANnDaOXCq12dk9MAy0xkM0VQLIvbUxjk&usp=drive_copy"
  },
  {
    "no": 93,
    "npsn": "20501861",
    "nama": "SMAS MUHAMMADIYAH 1 TAMAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Sidoarjo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1zlYkzIX57DJ0B1EFTB_8byvRVTVqpAwk"
  },
  {
    "no": 94,
    "npsn": "20540064",
    "nama": "SMAS MUHAMMADIYAH 2",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Sidoarjo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1iiEQPnWBW4yCnka23-aWdJKbT_9vqrUn"
  },
  {
    "no": 95,
    "npsn": "20522655",
    "nama": "SMAN 1 ASEMBAGUS",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Situbondo",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1eqdtRBXVfPfloMlVq0xoppjb935A57Ni&usp=drive_copy"
  },
  {
    "no": 96,
    "npsn": "20529970",
    "nama": "SMA NEGERI 1 GAPURA SUMENEP",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kab. Sumenep",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1ao13ZCqLFXSWl5x2pII0WQQ9zfa9trrp&usp=drive_copy"
  },
  {
    "no": 97,
    "npsn": "20535052",
    "nama": "SMAN 3 BLITAR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Blitar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1ZWqR2PasZtGj-tg34KK5Gd6IiDOmL0PZ&usp=drive_copy"
  },
  {
    "no": 98,
    "npsn": "20533667",
    "nama": "SMA NEGERI 4 KOTA MALANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Malang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1aFXYJM_SzlXB_YqqjgjHfiK4fwRL6D8P&usp=drive_copy"
  },
  {
    "no": 99,
    "npsn": "20554539",
    "nama": "SMAS BRAWIJAYA SMART SCHOOL",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Malang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1LVLFlokgYF29sRfxq9bAEL_4n_IMoZlQ&usp=drive_copy"
  },
  {
    "no": 100,
    "npsn": "20534749",
    "nama": "SMAN 2 Mojokerto",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Mojokerto",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1g8MKMSLpmbmI_biar3UUHxqXvuZBCYUD&usp=drive_copy"
  },
  {
    "no": 101,
    "npsn": "20534744",
    "nama": "SMAS PGRI 1",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Mojokerto",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1imQ1NEBH7xFW6w3-OwzaAIVL7ARX3vd4&usp=drive_copy"
  },
  {
    "no": 102,
    "npsn": "69900100",
    "nama": "SMA MUHAMMADIYAH 10 Surabaya",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Surabaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=16QN8uCdBF0QK9Io77qIqdwK4lDj2XR0t"
  },
  {
    "no": 103,
    "npsn": "20577229",
    "nama": "SMA VITA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Surabaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 104,
    "npsn": "20532247",
    "nama": "SMAN 4 SURABAYA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Surabaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1JtIIxrfxE9TWM6mdhP0lisB6QUGmaxEe&usp=drive_copy"
  },
  {
    "no": 105,
    "npsn": "20532248",
    "nama": "SMAN 5 SURABAYA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Surabaya",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1H61fbl3dkbGaDyOcT2XuGTASDbeQ1Umu/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=16-ouGL4ohdfvAbsDQvzvLSF1YTx7-hBy&usp=drive_copy"
  },
  {
    "no": 106,
    "npsn": "20532163",
    "nama": "SMAS MUHAMMADIYAH 2",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Jawa Timur",
    "kabkota": "Kota Surabaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1J6S6xHY9o9bIu80JaVVPfK4KgT7YDwzu"
  },
  {
    "no": 107,
    "npsn": "30100392",
    "nama": "SMAN 2 SAMBAS",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kab. Sambas",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18TJ3UUSH_vIVf5zRhia8VXgpqeGw52yt&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1C5zojtHNh0zwxqp4giFMFR8CT0UVmMCn&usp=drive_copy"
  },
  {
    "no": 108,
    "npsn": "30105074",
    "nama": "SMA KATOLIK SANTU PETRUS PONTIANAK",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kota Pontianak",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18TJ3UUSH_vIVf5zRhia8VXgpqeGw52yt&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1ecjLS5KANfuDXe2qcLir6nxmvIgRkgy3&usp=drive_copy"
  },
  {
    "no": 109,
    "npsn": "69981698",
    "nama": "SMAIT AL-MUMTAZ",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kota Pontianak",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1qQjezHtWwN5K21yYmt1sf4amaH9N-Xq2/view?usp=sharing"
  },
  {
    "no": 110,
    "npsn": "30105210",
    "nama": "SMAN 1 PONTIANAK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kota Pontianak",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18TJ3UUSH_vIVf5zRhia8VXgpqeGw52yt&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1YcTaVAwAwpqiub2qzs2DIq1Zt7RW5N5M&usp=drive_copy"
  },
  {
    "no": 111,
    "npsn": "30105468",
    "nama": "SMAN 1 SINGKAWANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kota Singkawang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18TJ3UUSH_vIVf5zRhia8VXgpqeGw52yt&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1XU6ORDspbZyiCSfeqAoMOu_cABTkdpUS&usp=drive_copy"
  },
  {
    "no": 112,
    "npsn": "30105463",
    "nama": "SMAS SANTO PAULUS SINGKAWANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Barat",
    "kabkota": "Kota Singkawang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 113,
    "npsn": "69830458",
    "nama": "SMA ISLAM TERPADU UKHUWAH BANJARMASIN",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Selatan",
    "kabkota": "Kota Banjarmasin",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1-a6w8bxbYbGvDoDriWiomLYmgnI7UmJz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1ghR1Rq3j6FkihZ_7EZrRWp_UuBicgIzE&usp=drive_copy"
  },
  {
    "no": 114,
    "npsn": "30304271",
    "nama": "SMAN 5 BANJARMASIN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Selatan",
    "kabkota": "Kota Banjarmasin",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1-a6w8bxbYbGvDoDriWiomLYmgnI7UmJz&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1uG3gGWzlCIa36JL9H_5eEGO9neUuNfUt&usp=drive_copy"
  },
  {
    "no": 115,
    "npsn": "30304468",
    "nama": "SMAS KRISTEN KANAAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Selatan",
    "kabkota": "Kota Banjarmasin",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 116,
    "npsn": "30304275",
    "nama": "SMAS PGRI 2 BANJARMASIN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Selatan",
    "kabkota": "Kota Banjarmasin",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1M8QpUhKsvogm1fu0kQ8fkxbqEMGtXyEq&usp=drive_copy"
  },
  {
    "no": 117,
    "npsn": "30203970",
    "nama": "SMAN 1 MUARA TEWEH",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Tengah",
    "kabkota": "Kab. Barito Utara",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1pIdTQGeOx-XNsisWNMxLAZhGpNVc48uL&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1pTJN0Zq9_KkurPkUUa1JUkbnjfZ8wBgN&usp=drive_copy"
  },
  {
    "no": 118,
    "npsn": "30202276",
    "nama": "SMAN 1 SEPANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Tengah",
    "kabkota": "Kab. Gunung Mas",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1pIdTQGeOx-XNsisWNMxLAZhGpNVc48uL&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=15VifkzbYzDbf3SdblSsOeCyr1WoM-LvJ&usp=drive_copy"
  },
  {
    "no": 119,
    "npsn": "30401491",
    "nama": "SMAN 1 BALIKPAPAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Timur",
    "kabkota": "Kota Balikpapan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1WzgJRJfyB77qk46jHMBN1t6bNRsruWia&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1UPdZJNtDsv23tfCQyvVJK7kGWipcgWsq&usp=drive_copy"
  },
  {
    "no": 120,
    "npsn": "69766189",
    "nama": "SMAS IT DAARUL HIKMAH",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Timur",
    "kabkota": "Kota Bontang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1zgu21qxlb0hABzAk5G6fkqC0uEWsPv3h/view?usp=sharing"
  },
  {
    "no": 121,
    "npsn": "69950015",
    "nama": "SMA Islam Terpadu Granada",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Kalimantan Timur",
    "kabkota": "Kota Samarinda",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1-GVKTeyu7NwXgTn00N2omGwhBY2VqjsC/view?usp=sharing"
  },
  {
    "no": 122,
    "npsn": "30401058",
    "nama": "SMA Negeri 3 Samarinda",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Timur",
    "kabkota": "Kota Samarinda",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1WzgJRJfyB77qk46jHMBN1t6bNRsruWia&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=151Rc75bdQ1S2lNaG7HAdhzw8uBh_UNU7&usp=drive_copy"
  },
  {
    "no": 123,
    "npsn": "30402593",
    "nama": "SMA NEGERI 1 TANJUNG PALAS",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kalimantan Utara",
    "kabkota": "Kab. Bulungan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1XiUsZ4tkNHPSzNdYeSYkA6I-OgHYsGPR/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/file/d/1xxEgg9oo-q-twHTGc8ckSBXFI9MoSO_f/view?usp=drive_link"
  },
  {
    "no": 124,
    "npsn": "10900232",
    "nama": "SMAN 1 SUNGAI LIAT",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kepulauan Bangka Belitung",
    "kabkota": "Kab. Bangka",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1io9UiAJaCBwoLzFMtvb8ACpIeJOJh65t/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=19hTSXJ_ODgpMT7C3gBpN1hfIEgX0UPxM&usp=drive_copy"
  },
  {
    "no": 125,
    "npsn": "11002049",
    "nama": "SMAN 2 BUNGURAN TIMUR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kepulauan Riau",
    "kabkota": "Kab. Natuna",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1EInXkysF1M4hf0D5uHtHFnAlXt2OSvkQ&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1EInXkysF1M4hf0D5uHtHFnAlXt2OSvkQ&usp=drive_copy"
  },
  {
    "no": 126,
    "npsn": "11002197",
    "nama": "SMAN 3 BATAM",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Kepulauan Riau",
    "kabkota": "Kota Batam",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1EInXkysF1M4hf0D5uHtHFnAlXt2OSvkQ&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1KvVy_Sw1_LdLG645Gko5WrsBp1PNvC7-&usp=drive_copy"
  },
  {
    "no": 127,
    "npsn": "10800700",
    "nama": "SMAN 2 KALIANDA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Lampung Selatan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1pSX_2v-CbV3LaPGtvy4V61SmO6sw24bm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1BKjulorkbFWRZMaXc4idlnNi9_smek7J&usp=drive_copy"
  },
  {
    "no": 128,
    "npsn": "10801967",
    "nama": "SMAN 1 BANGUNREJO",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Lampung Tengah",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1pSX_2v-CbV3LaPGtvy4V61SmO6sw24bm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1ptgWmZCf9RHXslUzzqS6CWg3jl47hs2B&usp=drive_copy"
  },
  {
    "no": 129,
    "npsn": "10802065",
    "nama": "SMAN 1 TERUSAN NUNYAI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Lampung Tengah",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1pSX_2v-CbV3LaPGtvy4V61SmO6sw24bm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1QdCt0m5LXwxepEGoM4PPcJgjw1c1Dhrt&usp=drive_copy"
  },
  {
    "no": 130,
    "npsn": "69763270",
    "nama": "SMAS IT BAITUL MUSLIM",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Lampung Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1caPrHsh9ZCuQTNddt13PMBd8n0FHhoqr/view?usp=sharing"
  },
  {
    "no": 131,
    "npsn": "10806005",
    "nama": "SMAS PGRI 2 MARGA TIGA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Lampung Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Q6O4WYIqX20MUspXdCwD_MTtQwOzhvVn&usp=drive_copy"
  },
  {
    "no": 132,
    "npsn": "10803535",
    "nama": "SMAN 1 PESISIR TENGAH",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kab. Pesisir Barat",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1pSX_2v-CbV3LaPGtvy4V61SmO6sw24bm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/13lSyHEzh0-ouWjSlDIRwvPRWL6YWv1Ke/view"
  },
  {
    "no": 133,
    "npsn": "10807063",
    "nama": "SMAN 2 BANDAR LAMPUNG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kota Bandar Lampung",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1pSX_2v-CbV3LaPGtvy4V61SmO6sw24bm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1NOy1Ei_-vOXbs3NGftQ2q6HApXDcjBEB&usp=drive_copy"
  },
  {
    "no": 134,
    "npsn": "70023899",
    "nama": "SMA MUHAMMADIYAH AHMAD DAHLAN METRO",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Lampung",
    "kabkota": "Kota Metro",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1tLYPGVYZM7UUqpKT-KJylQBYlXbIKdYz"
  },
  {
    "no": 135,
    "npsn": "60103695",
    "nama": "SMA Negeri 8 Kepulauan Tanimbar",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kab. Kepulauan Tanimbar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1KKRArwwm5HBs4NEANaTI6dcJ6VrVapEe&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1K5IVOfg1bPh2IBKWybsQke8V46E2HRDM&usp=drive_copy"
  },
  {
    "no": 136,
    "npsn": "69774664",
    "nama": "SMA Negeri 37 Maluku Tengah",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kab. Maluku Tengah",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KKRArwwm5HBs4NEANaTI6dcJ6VrVapEe&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=12xJmgHiPJpngVQdmzgecUau_bKyrpsTq&usp=drive_copy"
  },
  {
    "no": 137,
    "npsn": "60100816",
    "nama": "SMA SANATA KARYA LANGGUR",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kab. Maluku Tenggara",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 138,
    "npsn": "60102006",
    "nama": "SMAN 2 AMBON",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kota Ambon",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KKRArwwm5HBs4NEANaTI6dcJ6VrVapEe&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=15dNUyUVYHqpmHahGWwhbFD8aI_g3iVkl&usp=drive_copy"
  },
  {
    "no": 139,
    "npsn": "60102967",
    "nama": "SMAS PGRI 1 AMBON",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kota Ambon",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1bGcy3zH4hw5cNN82ulm7DnmxRArKbHqZ&usp=drive_copy"
  },
  {
    "no": 140,
    "npsn": "60102016",
    "nama": "SMAS XAVERIUS AMBON",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Maluku",
    "kabkota": "Kota Ambon",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 141,
    "npsn": "60200296",
    "nama": "SMAN 1 HALMAHERA UTARA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Maluku Utara",
    "kabkota": "Kab. Halmahera Utara",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1p56Ksv2DLAi2kQxG-SPfAUyRQuG1ydJb&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1o_5u86Um4DWXwaT271AHlW4wqNd1ootF&usp=drive_copy"
  },
  {
    "no": 142,
    "npsn": "60200720",
    "nama": "SMA NEGERI 4 KOTA TERNATE",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Maluku Utara",
    "kabkota": "Kota Ternate",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1p56Ksv2DLAi2kQxG-SPfAUyRQuG1ydJb&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1HHv29PFwJ0UG3NtlYbUtGpvoO5UTzilQ&usp=drive_copy"
  },
  {
    "no": 143,
    "npsn": "50203685",
    "nama": "SMAN 1 WOJA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Barat",
    "kabkota": "Kab. Dompu",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1h5ZGsprxX97uhZDFERrmMlaAso-vqIW4&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1QmdMrI2Dfj_4luQIlbndyoIeehmTkhaU&usp=drive_copy"
  },
  {
    "no": 144,
    "npsn": "50202411",
    "nama": "SMAN 1 PRINGGABAYA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Barat",
    "kabkota": "Kab. Lombok Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1h5ZGsprxX97uhZDFERrmMlaAso-vqIW4&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Nj62mnYEOWA-YDx_Ogc94_zK50R7FSJd&usp=drive_copy"
  },
  {
    "no": 145,
    "npsn": "50204729",
    "nama": "SMAN 4 KOTA BIMA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Barat",
    "kabkota": "Kota Bima",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1h5ZGsprxX97uhZDFERrmMlaAso-vqIW4&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1Z-dsUjIU1AsthdI_5Hwk6XXEWcQUL2qb&usp=drive_copy"
  },
  {
    "no": 146,
    "npsn": "50204515",
    "nama": "SMAN 5 MATARAM",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Barat",
    "kabkota": "Kota Mataram",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1h5ZGsprxX97uhZDFERrmMlaAso-vqIW4&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/14rx50EXGvTa3yGC0H-Hj9K37ApTbsvGJ/view?usp=drive_link"
  },
  {
    "no": 147,
    "npsn": "50301673",
    "nama": "SMA KATOLIK ST. YOSEPH KALABAHI",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Alor",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=17AjS1amyQ_VzM8S_hz9bSHW9-4y5OGeO&usp=drive_copy"
  },
  {
    "no": 148,
    "npsn": "50301404",
    "nama": "SMAN 1 ATAMBUA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Belu",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Wrg4CiU3Fybsnz6io5TbdHJQACUFporx/view?usp=drive_link"
  },
  {
    "no": 149,
    "npsn": "50304407",
    "nama": "SMAS PGRI SWASTHIKA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Lembata",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1kLD4UKQgaLiUJKTAJZyGfSNh5xquen8a&usp=drive_copy"
  },
  {
    "no": 150,
    "npsn": "50303422",
    "nama": "SMAS SETIA BAKTI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Manggarai",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 151,
    "npsn": "50303423",
    "nama": "SMAS ST FRANSISKUS XAVERIUS",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Manggarai",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 152,
    "npsn": "50304772",
    "nama": "SMAS ST FAMILIA WAE NAKENG",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Manggarai Barat",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=14fPVrWI8SijjoUKlfQUuAoQb9cpBsreR&usp=drive_copy"
  },
  {
    "no": 153,
    "npsn": "50310689",
    "nama": "SMAN 6 Kota Komba",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Manggarai Timur",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1wb-CorF2EvP0BKIbwF00RSk7EW05xi2r/view?usp=sharing"
  },
  {
    "no": 154,
    "npsn": "50302314",
    "nama": "SMAS KATOLIK  ST. JOHN PAUL II MAUMERE",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Sikka",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1i80Ns7VcyxnvHDjzMwcwkuuCjKqUUo_J&usp=drive_copy"
  },
  {
    "no": 155,
    "npsn": "50304081",
    "nama": "SMAN 1 Wewewa Timur",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Sumba Barat Daya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1VxEnAXABkwX0X7UiYS-F2NBd4KXeigEq/view?usp=sharing"
  },
  {
    "no": 156,
    "npsn": "50303792",
    "nama": "SMA NEGERI 1 LEWA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Sumba Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1NFSQ4L6aY4gP2KOT4mWwdg2b_3B3EXR8/view?usp=drive_link"
  },
  {
    "no": 157,
    "npsn": "50303793",
    "nama": "SMA PGRI WAINGAPU",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kab. Sumba Timur",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1nq0lRAqvxCh5vDcP-vX6exI-x2w4gX6-&usp=drive_copy"
  },
  {
    "no": 158,
    "npsn": "69896535",
    "nama": "SMA Kristen Citra Bangsa Mandiri",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kota Kupang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 159,
    "npsn": "50304947",
    "nama": "SMAN 5 KUPANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Nusa Tenggara Timur",
    "kabkota": "Kota Kupang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1TX-BRmrKutEJPnNIfbgkyeNcwNg-81gx/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1m2m-NVch_ianw61W0nH1dRXqrjSAFMwp/view?usp=drive_link"
  },
  {
    "no": 160,
    "npsn": "60301018",
    "nama": "Sekolah Negeri Khusus Sains dan Bahasa Papua",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua",
    "kabkota": "Kota Jayapura",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1AENY3owY2pAUrmkCZJu5FF-LfsOZ6U6i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1NvcnJdyDAYUJPgelPFdWUIbC3vN3M3YE&usp=drive_copy"
  },
  {
    "no": 161,
    "npsn": "60301005",
    "nama": "SMAS KRISTEN KALAM KUDUS",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Papua",
    "kabkota": "Kota Jayapura",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 162,
    "npsn": "60301015",
    "nama": "SMAS YPPK TERUNA BAKTI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Papua",
    "kabkota": "Kota Jayapura",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 163,
    "npsn": "60401125",
    "nama": "SMA Negeri 2 Fakfak",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua Barat",
    "kabkota": "Kab. Fak Fak",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1b-PCVNp8WIvPto0ReTQEcGS9FOn2CtAH/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/file/d/1aj4sLC-Zruqll5dutS4jeSpFz9m6H_P_/view?usp=drive_link"
  },
  {
    "no": 164,
    "npsn": "60403707",
    "nama": "SMAN 3 Kota Sorong",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua Barat Daya",
    "kabkota": "Kota Sorong",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1Gc2S_BUQGGJ-wgHZf1AaI-SB0eboDQlm&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1_-Wpg1Uex1LBFCZP-mitnHcc06INlqvq&usp=drive_copy"
  },
  {
    "no": 165,
    "npsn": "60301592",
    "nama": "SMAN 1 WAMENA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua Pegunungan",
    "kabkota": "Kab. Jayawijaya",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1BtX1nimyI9RfT5Hj7fohXDtMQ6nP5-AF&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1QTRyO4GEOIZ_r2elH51SyUHmAeD3tmYf&usp=drive_copy"
  },
  {
    "no": 166,
    "npsn": "60300625",
    "nama": "SMA NEGERI 1 MERAUKE",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua Selatan",
    "kabkota": "Kab. Merauke",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1vBTD477XZQ9GCgGzX66VofQr11laPzoW&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1OGUudKdepXfKIMZP3dqa16RJGUIa4L23/view?usp=sharing"
  },
  {
    "no": 167,
    "npsn": "60300593",
    "nama": "SMA YPPK YOANES XXIII MERAUKE",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Papua Selatan",
    "kabkota": "Kab. Merauke",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 168,
    "npsn": "60300796",
    "nama": "SMA Negeri 1 Nabire",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Papua Tengah",
    "kabkota": "Kab. Nabire",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1x_ZE36VTPGndubtHv1KFkmvuikxB2-Nf/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1je8nbLf5-4bidSKp2RIQMoGEBMY7Flkq&usp=drive_copy"
  },
  {
    "no": 169,
    "npsn": "10402076",
    "nama": "SMAN 1 KATEMAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Riau",
    "kabkota": "Kab. Indragiri Hilir",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11gu8WOmYI3zw7PQWlK810hP0g-ZfvQKL&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=11gu8WOmYI3zw7PQWlK810hP0g-ZfvQKL&usp=drive_copy"
  },
  {
    "no": 170,
    "npsn": "10400365",
    "nama": "SMA NEGERI 1 BANGKINANG KOTA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Riau",
    "kabkota": "Kab. Kampar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1oSaYZ8vdYKkVlO5ZXV9DB0OzI3axYSu0/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1TPTamgP-x_S_ApThjWgXTYbMdGIoVDKX&usp=drive_copy"
  },
  {
    "no": 171,
    "npsn": "10403796",
    "nama": "SMAN 1 TELUK KUANTAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Riau",
    "kabkota": "Kab. Kuantan Singingi",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=11gu8WOmYI3zw7PQWlK810hP0g-ZfvQKL&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1O_6H9tddEfQxWZX3NpZfcgUmt-DxD8L3/view?usp=drive_link"
  },
  {
    "no": 172,
    "npsn": "69899651",
    "nama": "SMA Negeri 16 Pekanbaru",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Riau",
    "kabkota": "Kota Pekanbaru",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1Bc_SIVgyww1Daq2cWFU6m9j0KJhPIhfF/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Hw2ZtBpe3UIpv8_EWIWOF5yI39JPJemC/view?usp=sharing"
  },
  {
    "no": 173,
    "npsn": "10403993",
    "nama": "SMAS MUHAMMADIYAH 1 Pekanbaru",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Riau",
    "kabkota": "Kota Pekanbaru",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1LE0yjHCW6EOzI-K6MtiC6tImTq7rCzqJ"
  },
  {
    "no": 174,
    "npsn": "40600653",
    "nama": "UPTD SMAN 2 POLEWALI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Barat",
    "kabkota": "Kab. Polewali Mandar",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1MpJSQl6QOfFO3QPqRrDqjKP0YpwUmpm8/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1e3HOer2dL7sdvrPQl0_qBls7wRmiaslt/view?usp=drive_link"
  },
  {
    "no": 175,
    "npsn": "40302552",
    "nama": "SMAN 1 BONE",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kab. Bone",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1SIrdyx2TrQAtD-09vK3l78VITALsUu3i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=17AGfCxVk3JGqq3-SjKrfgGphhp2USbyV&usp=drive_copy"
  },
  {
    "no": 176,
    "npsn": "40301037",
    "nama": "SMAN 5 GOWA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kab. Gowa",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1SIrdyx2TrQAtD-09vK3l78VITALsUu3i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1pdavlM9bOA_n1a96BLBakYJgfxB2kAVS&usp=drive_copy"
  },
  {
    "no": 177,
    "npsn": "69761930",
    "nama": "SMAN 11 PINRANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kab. Pinrang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1SIrdyx2TrQAtD-09vK3l78VITALsUu3i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1KdojzhUTJT2kEuFuyk8wFPAA9InHDizx&usp=drive_copy"
  },
  {
    "no": 178,
    "npsn": "40306507",
    "nama": "SMAS KRISTEN BARANA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kab. Toraja Utara",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 179,
    "npsn": "40303176",
    "nama": "SMAN 2 WAJO",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kab. Wajo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1SIrdyx2TrQAtD-09vK3l78VITALsUu3i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=11HGoyBjSRG9fWmMAwHFevfs18JB7G1z2&usp=drive_copy"
  },
  {
    "no": 180,
    "npsn": "40307236",
    "nama": "SMA FRATER MAKASSAR",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kota Makassar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 181,
    "npsn": "40311951",
    "nama": "SMAN 17 MAKASSAR",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kota Makassar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1SIrdyx2TrQAtD-09vK3l78VITALsUu3i&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1198XsqrKFCNl0ykeAPuRvgTU0XFBaxgq&usp=drive_copy"
  },
  {
    "no": 182,
    "npsn": "40311938",
    "nama": "SMAS KATOLIK CENDRAWASIH",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kota Makassar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 183,
    "npsn": "40307369",
    "nama": "SMAS KATOLIK RAJAWALI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Selatan",
    "kabkota": "Kota Makassar",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 184,
    "npsn": "40201628",
    "nama": "SMAN 1 TOILI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Tengah",
    "kabkota": "Kab. Banggai",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18uP90RIfIODNejqt03nZDw9UfjNk3_4L&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1gcw-x67L-jxb_g0_JXf_1fZ4GNgXjulx&usp=drive_copy"
  },
  {
    "no": 185,
    "npsn": "40201331",
    "nama": "SMAS GKST 2 TENTENA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Tengah",
    "kabkota": "Kab. Poso",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1qCE8uBM8r7BoS50-bGshR5lKdihzrgI_/view?usp=drive_link"
  },
  {
    "no": 186,
    "npsn": "40203611",
    "nama": "SMAN 4 PALU",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Tengah",
    "kabkota": "Kota Palu",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=18uP90RIfIODNejqt03nZDw9UfjNk3_4L&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1Dagl8Kyj5lXLWqACwYAStjycHOtn3WcT/view?usp=drive_link"
  },
  {
    "no": 187,
    "npsn": "40404032",
    "nama": "SMA NEGERI 03 BOMBANA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Tenggara",
    "kabkota": "Kab. Bombana",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1aWVKg6IyDsYa0_VP0uT6bH7Knxk0r0IO&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1uUAUFvkdAP2yIKjG1QCv7lSa8zJpU1Qi/view?usp=sharing"
  },
  {
    "no": 188,
    "npsn": "40402619",
    "nama": "SMAN 1 KENDARI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Tenggara",
    "kabkota": "Kota Kendari",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1aWVKg6IyDsYa0_VP0uT6bH7Knxk0r0IO&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1WV5-v4Su77OBqOwC-T3qFsNzp2wX1XUj&usp=drive_copy"
  },
  {
    "no": 189,
    "npsn": "40402616",
    "nama": "SMAN 4 KENDARI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Tenggara",
    "kabkota": "Kota Kendari",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1aWVKg6IyDsYa0_VP0uT6bH7Knxk0r0IO&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1ZwmwjIV-fQ5ce5RtWsaFN48UMaMrRomC/view?usp=sharing"
  },
  {
    "no": 190,
    "npsn": "40100325",
    "nama": "SMA NEGERI 1 BOLANG ITANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Utara",
    "kabkota": "Kab. Bolaang Mongondow Utara",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1lbJkRzJl3KpnL2z4ioyT1wTg3gRQ3z_6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1o_kYAMfRHAiE_Fz0eOW8bL4xyA-yrvc1&usp=drive_copy"
  },
  {
    "no": 191,
    "npsn": "70011015",
    "nama": "SMA BETZATA LEILEM",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Utara",
    "kabkota": "Kab. Minahasa",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 192,
    "npsn": "40102618",
    "nama": "SMAN 1 MANADO",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sulawesi Utara",
    "kabkota": "Kota Manado",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1lbJkRzJl3KpnL2z4ioyT1wTg3gRQ3z_6/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/10GlRYGScAtxHIDHklBTBaVOrDFrdihAL/view?usp=drive_link"
  },
  {
    "no": 193,
    "npsn": "40103169",
    "nama": "SMAS KATOLIK KARITAS TOMOHON",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Utara",
    "kabkota": "Kota Tomohon",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 194,
    "npsn": "40103174",
    "nama": "SMAS LOKON ST NIKOLAUS TOMOHON",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sulawesi Utara",
    "kabkota": "Kota Tomohon",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 195,
    "npsn": "10301592",
    "nama": "SMAN 1 GUNUNG TALANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Barat",
    "kabkota": "Kab. Solok",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1DlO4IZtM8SFwhDvpWS1bzxsTxpNja15A/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1wssteCGCMKjFgR9blV6kMrczzsqlU-ml&usp=drive_copy"
  },
  {
    "no": 196,
    "npsn": "10303499",
    "nama": "SMAN 2 PADANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Barat",
    "kabkota": "Kota Padang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1DlO4IZtM8SFwhDvpWS1bzxsTxpNja15A/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1wTO_wNpLiN8_QrlonfHqZrAEjBg_2nZa&usp=drive_copy"
  },
  {
    "no": 197,
    "npsn": "10303503",
    "nama": "SMAN 6 PADANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Barat",
    "kabkota": "Kota Padang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1DlO4IZtM8SFwhDvpWS1bzxsTxpNja15A/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1U3wwNAyJ1vzeHrV5X8ZPkpp01Vt70Qam&usp=drive_copy"
  },
  {
    "no": 198,
    "npsn": "10646031",
    "nama": "SMA PGRI GELUMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kab. Muara Enim",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1OP3DXaO7DoTePONxq45-U7bBxxf0Yuxx&usp=drive_copy"
  },
  {
    "no": 199,
    "npsn": "10601972",
    "nama": "SMAN 1 MUARA BELITI",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kab. Musi Rawas",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1St32vdmZvJdhjVuMVAOh41p8v9YGuiM-&usp=drive_copy"
  },
  {
    "no": 200,
    "npsn": "10643818",
    "nama": "SMA NEGERI 1 INDRALAYA UTARA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kab. Ogan Ilir",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/file/d/1KrCNV1R45dVsGOCBIx7XUc7spqkPBq0n/view?usp=drive_link"
  },
  {
    "no": 201,
    "npsn": "10600559",
    "nama": "SMAN 1 KAYUAGUNG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kab. Ogan Komering Ilir",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1hHpIXuzzxscBrt8n0QF98dBVxvtSsOYH&usp=drive_copy"
  },
  {
    "no": 202,
    "npsn": "10606617",
    "nama": "SMAN 1 SEMENDAWAI SUKU III",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kab. Ogan Komering Ulu Timur",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1o4kSps37l3luYr_JcWqYun16rVMV7Dei&usp=drive_copy"
  },
  {
    "no": 203,
    "npsn": "10609873",
    "nama": "SMAN 4 PAGAR ALAM",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Pagar Alam",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/file/d/1FQxfcqWzE8j7A1iNjoV0wU5XpsW_B-s6/view?usp=drive_link"
  },
  {
    "no": 204,
    "npsn": "10648903",
    "nama": "SMA IT AL FURQON PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1LBMQ-MCUViZPItDQp_PgefOmHtJ7r0q2/view?usp=sharing"
  },
  {
    "no": 205,
    "npsn": "10604065",
    "nama": "SMA MUHAMMADIYAH 01 PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1byr9aKfG2lo7qir-JJZomvO_-XQe1Yoi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1E-i3Gc_mdIv20T33b5lDLLQGjLmC_rf6"
  },
  {
    "no": 206,
    "npsn": "10603858",
    "nama": "SMA NEGERI 17 PALEMBANG",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/18X9PFRfQDR9VpeTZZjNRDVDgzo1ogqAE/view?usp=drive_link",
    "link_kesiapan": "https://drive.google.com/open?id=1IkcNCjO5jAXTh6kXizUDSBavq70qZ2vO&usp=drive_copy"
  },
  {
    "no": 207,
    "npsn": "10609675",
    "nama": "SMA PGRI 01 PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1pral9TS3fA9HJZZkcNuohCQEZklKFYYi&usp=drive_copy"
  },
  {
    "no": 208,
    "npsn": "10609676",
    "nama": "SMA PGRI 02 PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1OivJfBQ1k4Ufuq4VivSseXWgILDFLgN_&usp=drive_copy"
  },
  {
    "no": 209,
    "npsn": "10609679",
    "nama": "SMA PGRI 04 PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1tzUKgOPax5BmQ8o062E7azZVg09clrf5&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1EzcmiUxd5xGxBsi18wgh_YDMIWtK9g2f&usp=drive_copy"
  },
  {
    "no": 210,
    "npsn": "10609707",
    "nama": "SMA XAVERIUS 04 PALEMBANG",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Selatan",
    "kabkota": "Kota Palembang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 211,
    "npsn": "10204053",
    "nama": "SMAN 2 KISARAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Asahan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=19oiJo9hCrCTbx7mkPGlVwM1oz58f6WWQ&usp=drive_copy"
  },
  {
    "no": 212,
    "npsn": "10214136",
    "nama": "SMAN 1 PERCUT SEI TUAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Deli Serdang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1bd4Rk3D5Ny-j2QWkPtv_Pm-dy1Jo3Jrj/view?usp=drive_link"
  },
  {
    "no": 213,
    "npsn": "10220218",
    "nama": "SMAN 1 SUNGGAL",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Deli Serdang",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/131amJwLn8OXos7xOpGEdQ3yf__mWNc7U/view?usp=drive_link"
  },
  {
    "no": 214,
    "npsn": "10201985",
    "nama": "SMA NEGERI 1 KABANJAHE",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Karo",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing"
  },
  {
    "no": 215,
    "npsn": "10259405",
    "nama": "SMAN 3 PANYABUNGAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Mandailing Natal",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1tH9GUZh23-IGQDuYlOcozrCB6EyGztRf/view?usp=drive_link"
  },
  {
    "no": 216,
    "npsn": "10259031",
    "nama": "SMAN 1 ALASA",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Nias Utara",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1UzE8V2M1mgAr8B97NPodHoSlW-BaOGD_/view?usp=drive_link"
  },
  {
    "no": 217,
    "npsn": "69831535",
    "nama": "SMA SWASTA BINA ARTHA",
    "status": "Swasta",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Padang Lawas utara",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/open?id=1gvQukvAbjW7x69cvArCuJFITACZKT1k2&usp=drive_copy"
  },
  {
    "no": 218,
    "npsn": "10257749",
    "nama": "SMAN 1 PEGAJAHAN",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Serdang Bedagai",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/19xyMOvYiqxinP_xonxs3unmjoG-keuqH/view?usp=drive_link"
  },
  {
    "no": 219,
    "npsn": "10207063",
    "nama": "SMA NEGERI 2 PLUS SIPIROK",
    "status": "Negeri",
    "pengusul": "Dinas Pendidikan",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kab. Tapanuli Selatan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/file/d/1wcGNwJdNoxXFzK_ITu6N2rBHa4P43DTX/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1v_ciWP1lLB-liDtm-ZLadhOHPrtegusV/view?usp=drive_link"
  },
  {
    "no": 220,
    "npsn": "10212766",
    "nama": "SMA SWASTA KRISTEN BNKP GUNUNGSITOLI",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kota Gunungsitoli",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=1CA8rE5uIw06FnvzUL6E5yu_mJZAcqGwi&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/open?id=1T35GH96_tXx4SJnv6ia27AA63y7pVjG6&usp=drive_copy"
  },
  {
    "no": 221,
    "npsn": "10210923",
    "nama": "SMA SWASTA SANTO THOMAS 1 MEDAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kota Medan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/file/d/1o_UpxwsqmRuB8GHoSyU9DvgaOfbh4D2g/view?usp=sharing",
    "link_kesiapan": "https://drive.google.com/file/d/1Z2falKHAAdR7QxCcrP2gSYMKckPD4Ttf/view?usp=sharing"
  },
  {
    "no": 222,
    "npsn": "10261760",
    "nama": "SMAS AL FITYAN",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kota Medan",
    "kka": "Tidak",
    "link_rekomendasi": "https://drive.google.com/open?id=11IQjh2EQtzL_WJQqMnrRpCsqm6sKUyIw&usp=drive_copy",
    "link_kesiapan": "https://drive.google.com/file/d/1AarIPmhqxIBbaFFZxGwz6V5-_JtvNEi-/view?usp=sharing"
  },
  {
    "no": 223,
    "npsn": "10210882",
    "nama": "SMAS NAHDATUL ULAMA",
    "status": "Swasta",
    "pengusul": "Mitra",
    "provinsi": "Prov. Sumatera Utara",
    "kabkota": "Kota Medan",
    "kka": "Ya",
    "link_rekomendasi": "https://drive.google.com/open?id=1KBY_pWpfxcIPDG5sjLMC9nFy8vBukMQp&usp=drive_copy",
    "link_kesiapan": null
  }
];

const BERANDA_SUMMARY = {
  "total": 223,
  "negeri": 125,
  "swasta": 98,
  "dinas_total": 140,
  "mitra_total": 83,
  "dinas_negeri": 125,
  "dinas_swasta": 15,
  "mitra_negeri": 0,
  "mitra_swasta": 83,
  "mapel_kka": 70,
  "dinas_link_rek_ada": 140,
  "dinas_link_kesiapan_ada": 140,
  "mitra_link_rek_ada": 83,
  "mitra_link_kesiapan_ada": 81,
  "charts": {
    "dinas_rek_ada_pct": 100.0,
    "dinas_kes_ada_pct": 100.0,
    "mitra_rek_ada_pct": 100.0,
    "mitra_kes_ada_pct": 97.6
  }
};
